name: Create index file

on:
    workflow_dispatch:
    push:
        branches:
            - main
        paths:
            - docs/ArchitectureDriver/*.md
            - docs/TopLevelRequirements/*.md

jobs:
    create-index:
        runs-on: ubuntu-latest
        timeout-minutes: 3

        permissions:
            contents: write
            repository-projects: read
        
        steps:
            - name: Check out main repo
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.x'
            
            - name: Changed files
              id: changed-files
              uses: tj-actions/changed-files@v45

            - name: Create index files
              env: 
                CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
                GH_TOKEN: ${{ github.token }}
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"

                create_index() {
                  local dir=$1
                  local index_file=$2
                  local category=$3
                  echo ${CHANGED_FILES}
                  if echo "${CHANGED_FILES}" | grep -q "^${dir}/"; then
                    echo "Creating ${index_file}"
                    echo "# ${category} Index" > ${index_file}
                    for file in ${dir}/*.md; do
                      echo "- [$(basename $file)]($file)" >> ${index_file}
                    done
                    git add ${index_file}
                  fi
                }

                create_index "docs/ArchitectureDriver" "docs/AD_index.md" "アーキテクチャドライバー"
                create_index "docs/TopLevelRequirements" "docs/TLR_index.md" "トップレベル要求"

                git commit -m "Update index files" || true
                git push origin main




