name: Test Statement

on:
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: test statement
              run: |
                files="docs/ArchitectureDocument/RMS.md"
                files+=" "
                files+="dosc/ArchitectureDocument/RMS.md"
                files+=" "
                files+="doc/ArchitectureDocument/RMS.md"
                echo ${files}          
                for file in ${files}; do
                    echo "File: ${file}"
                    if [[ "${file}" =~ "docs/" ]]; then
                        echo "Matched"
                    elif [[ "${file}" =~ "docs/ArchitectureDocument/" ]]; then
                        echo "Sub Matched"
                    else
                        echo "Not Matched"
                    fi
                done