name: Wiki

on:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Always succeed
        run: |
          check_flag=true
          default_flag=false
          echo $check_flag
          echo $default_flag